general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 320, 55
    position = 0, -80
    halign = center
    valign = center
}
